[package]
description = "Deprecated: Please use [Rust CBOR Lite](https://crates.io/crates/cbor_lite) or [serde_cbor](https://crates.io/crates/serde_cbor)"
license = "MIT"
name = "cbor-no-std"
version = "0.2.0"
authors = ["Mason Fischer <mason@kissr.co>"]
